#include <iostream>
#include <filesystem>

// Generated by CMake
#include "config.hpp"

#ifdef USE_MYMATH
    #include "math/my_math.hpp"
#else
    #include <cmath>
#endif

namespace fs = std::filesystem;

int main()
{
    std::string input;
    std::cout << "Fala, galera!" << std::endl;
    std::cin >> input;

    const double value = std::stod(input);
    std::cout << "Número fornecido: " << value << std::endl;
    fs::path fpath = "/";
    unsigned int number = value;
    std::cout << fpath << " " << number << std::endl;

    #ifdef USE_MYMATH
    double sqroot = util::math::mySqrt(value);
    std::cout << "Math do projeto" << std::endl;
    #else
    double sqroot = sqrt(value);
    std::cout << "Math std" << std::endl;
    #endif
        
    std::cout << "Sua raiz aproximada: " << sqroot << std::endl;
    std::cout << "Versão brasileira " << VERSION_MAJOR << "." << VERSION_MINOR << std::endl;
}